spring.application.name=currency-conversion
spring.config.import=optional:configserver:http://localhost:8888
server.port=8100

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# API-GATEWAY ERROR
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost