spring.application.name=limits_service
spring.config.import=optional:configserver:http://localhost:8888
# Instead of having the limit values hard-coded, take them from here:
limits-service.minimum=1
limits-service.maximum=1042