spring.application.name=limits-service
spring.config.import=optional:configserver:http://localhost:8888
# Configuring profiles:
spring.profiles.active=uat
# This one takes priority:
spring.cloud.config.profile=prod

# This was substituted by the Config Server + git local repo
# Make use of a Configuration Class:
limits-service.minimum=2
limits-service.maximum=998